### ISSUE TITLE
Feature request: enable dark mode when using a dark GTK theme

### ISSUE THREAD

**Issue by nicocarbone** [hugolabe/Wike#46] opened 2021-08-26 20:59 UTC
Thank you for wike! Is a really nice little app that I am enjoying a lot. 

I would like to ask for a feature: I would be really nice if wike enabled dark mode when a dark GTK theme is been used.

I have my ubuntu install configured to change to yaru-dark at sunset and many apps and webpages (all of them if using Dark Reader on Firefox) also change to dark mode when the gtk theme is changed. Wike does not and it would be really nice if it did.
It is not a big deal to enable it manually, but it would be a nice quality of life improvement if is easily doable.

**Comment by hugolabe** [comment] 2021-09-04 10:04
I find it an interesting feature that Wike can automatically switch to dark mode. The problem is that today GNOME does not really support a dark mode, although it does seem that it [will be implemented](https://discourse.gnome.org/t/libadwaita-1-0-roadmap/7415) in the future.

One option would be to change it when the Night Light mode is activated, but I don't know if it is the most suitable.

In any case, I will investigate the subject a little more.

**Comment by nicocarbone** [comment] 2021-09-04 18:11
AFAIK, what some apps do is detect when a dark variant of the GTK theme is
running and act accordingly. For example, enable dark mode when Yaru-dark
is the selected GTK Theme in Ubuntu.

I don't know how easy is this or if this is some kind of not officially
supported hack, though.

**Comment by hugolabe** [comment] 2021-09-04 18:26
I think they do this by checking the theme name to see if it contains the string 'dark'. It certainly doesn't seem like an official way but I have to look a bit more.

**Comment by nicocarbone** [comment] 2021-09-05 16:01
Great. Thanks! :)

**Comment by IngrownMink4** [comment] 2022-04-01 10:35
GNOME have already implemented the API and it's available in [GNOME 42](https://release.gnome.org/42/):

 https://gitlab.gnome.org/GNOME/libadwaita/-/issues/52

**Comment by hugolabe** [comment] 2022-04-01 10:54
> GNOME have already implemented the API and it's available in [GNOME 42](https://release.gnome.org/42/):
> 
> https://gitlab.gnome.org/GNOME/libadwaita/-/issues/52

Yes. This feature will be included in version 2 of Wike.
![wike2-system-dark](https://user-images.githubusercontent.com/18441950/161250041-403eb778-3b58-49ee-926b-43186b54cdae.png)

**Comment by hugolabe** [comment] 2022-05-23 16:39
Implemented in commit 0889dda8f29d65177bf074813f4e6bb9b4995b39
Soon in a new release
![wike-system-theme](https://user-images.githubusercontent.com/18441950/169867127-9fe78ebb-d4cd-499c-b677-f88d8834759e.png)

**Closed** 2022-05-28 09:24 UTC
Labels: enhancement
