### ISSUE TITLE
Don't add Main Page to recent articles

### ISSUE THREAD

**Issue by vanillajonathan** [hugolabe/Wike#76] opened 2022-04-01 16:35 UTC
Don't add the Wikipedia "Main Page" to the recent articles list.

It just adds noise and reduces the usability of the recent articles list.

**Comment by hugolabe** [comment] 2022-04-04 14:18
Yes. It seems correct that the Main Page is not saved in the list of recent articles.

The problem is how to detect that it’s the Main Page, since the URL is different for each of the Wikipedia languages.

To load the main page, the Wikipedia base URL is used (eg, https://en.wikipedia.org/), but this redirects to the real URL (https://en.wikipedia.org/wiki/Main_Page), which is the one that is saved in history and is different for each language (for example, in Spanish is https://es.wikipedia.org/wiki/Wikipedia:Portada)

To be able to check it, it would be necessary to create a list with all the possible URLs, which are many (as many as languages), and compare with the entire list.

**Comment by vanillajonathan** [comment] 2022-04-04 20:13
Maybe it would be possible to detect the redirect page from the base URL?
It will return a response with the status code 301 Moved Permanently and include a "Location" HTTP header.

Else I would be fine with just adding an exception for the Main Page on the English language Wikipedia. It wouldn't be a perfect solution, but it would be a quick, simple and easy fix that provide real value to most users.

**Comment by hugolabe** [comment] 2022-05-14 11:03
Fixed in commit 8ecf0a3a211caf8d2c99baf572a6f3a0263b93c3. I've done it by checking the URL before the redirect occurs, so it works with all languages.

**Closed** 2022-05-28 09:25 UTC
